import appleImg from './assets/redApple.jpg';
import * as data from './sample.json'
import fujiApple from './assets/fuji-apple.jpg'
import galaApple from './assets/gala-apple.jpg'
import goldenDeliciousApple from './assets/golden-delicious-apple.jpg'
import grannySmithApple from './assets/granny-smith-apple.jpg'
import redDeliciousApple from './assets/red-delicious-apple.jpg'
import beets from './assets/beetss.png'
import broccoli from './assets/broccoli.jpg'
import cantaloupe from './assets/cantaloupe.jpg'
import carrots from './assets/carrots.jpg'
import celery from './assets/celery.jpg'
import cucumber from './assets/cucumber.jpg'
import ginger from './assets/ginger.jpg'
import greenGrapes from './assets/green-grapes.jpg'
import redGrapes from './assets/red-grapes.jpg'
import blackGrapes from './assets/black-grapes.jpg'
import grapefruit from './assets/grapefruit.jpg'
import honeydew from './assets/honeydew.jpg';
import kale from './assets/kale.jpg'
import kiwi from './assets/kiwi.jpg'
import lemons from './assets/lemons.jpg'
import icebergLettuce from './assets/iceberg-lettuce.jpg'
import romaineLettuce from './assets/romaine-lettuce.jpg'
import lime from './assets/lime.jpg'
import oranges from './assets/oranges.jpg'
import parsley from './assets/parsley.jpg'
import pineapple from './assets/pineapple.jpg'
import peaches from './assets/peaches.jpg'
import pears from './assets/pears.jpg'
import strawberries from './assets/strawberries.jpg'
import tomatoes from './assets/tomatoes.jpg'
import turmeric from './assets/turmeric.jpg'
import watermelon from './assets/watermelon.jpg'

export const minerals = {
    vitaminA : "Vitamin A",
    vitaminB6: 'Vitamin B6',
    vitaminB12: 'Vitamin B12',
    vitaminC: 'Vitamin C',
    vitaminD: 'Vitamin D',
    vitaminE: 'Vitamin E',
    vitaminK: 'Vitamin K',
    biotin: 'Biotin',
    calcium: 'Calcium',
    chloride: 'Chloride',
    choline: 'Choline',
    chromium: 'Chromium',
    cholesterol: 'Cholesterol',
    copper: 'Copper',
    folate: 'Folate',
    iodine: 'Iodine',
    iron: 'Iron',
    magnesium: 'Magnesium',
    manganese: 'Manganese',
    molybdenum: 'Molybdenum',
    niacin: 'Niacin',
    pantothenicAcid: 'Pantothenic Acid',
    phosphorus: 'Phosphorus',
    potassium: 'Potassium',
    protein: 'Protein',
    riboflavin: 'Riboflavin',
    saturatedFat: 'Saturated Fat',
    selenium: 'Selenium',
    sodium: 'Sodium',
    thiamin: 'Thiamin',
    totalCarbohydrate: 'Total Carbohydrate',
    totalFat: 'Total Fat',
    zinc: 'Zinc'
};

//const list = [data];
export const dailyRecommendation = {
    vitaminA : "900mcg",
    vitaminB6: '1.7mg',
    vitaminB12: '2.4mcg',
    vitaminC: '90mg',
    vitaminD: '20mcg',
    vitaminE: '15 mg',
    vitaminK: '120mcg',
    biotin: '30mcg',
    calcium: '1300mg',
    chloride: '2300mg',
    choline: '550mg',
    chromium: '35mcg',
    cholesterol: '300mg',
    copper: '0.9mg',
    folate: '400mcg',
    iodine: '150mcg',
    iron: '18mg',
    magnesium: '420mg',
    manganese: '2.3mg',
    molybdenum: '45mcg',
    niacin: '16mg',
    pantothenicAcid: '5mg',
    phosphorus: '1250mg',
    potassium: '4700mg',
    protein: '50g',
    riboflavin: '1.3mg',
    saturatedFat: '20g',
    selenium: '55mcg',
    sodium: '2300mg',
    thiamin: '1.2mg',
    totalCarbohydrate: '275g',
    totalFat: '78g',
    zinc: '11mg'
};
const list = [
    {
        name: 'Fuji Apple',
        img: fujiApple,
        taste: "sweetest",
        calories: 18,
        totalFat: '0.05g',
        sodium: '0.3mg',
        totalCarbohydrate: '4.3g',
        sugar: '3.3g',
        protein: '0.1g',
        vitamins: {
            vitaminA: '0.57mcg',
            vitaminB3: '0.020mcg',
            vitaminB6: '0.013mg',
            vitaminE: '0.05mg',
            vitaminK: '0.3mcg',
            choline: '1.0mg',
            calcium: '1.98mg',
            copper: '0.007mg',
            magnesium: '1.42mg',
            manganese: '0.009mg',
            phosphorus: '3.69mg',
            potassium: '30.90mg',
        },
        facts:["Apples have slightly different nutrients depending on their type and color.",
        "an apple hybrid created by in Fujisaki, Aomori, Japan in late 1930s.",
        'The Fuji apple has the highest overall concentration of bioflavonoids out of all apples.  Bioflavonoids protect you from diseases',
        "One study found that drinking apple juice reduced the production of beta-amyloid in mice", "sweet flavor", "Heart and liver health", 
        "antioxidant and anti-inflammatory properties", "Improve insulin resistance"],
        shortFacts: ["Source of stuff", "Good for this and that, that, and this.", 'It taste good!'],
        "minerals": {
            magnesium: 0.06
        },
        'color': "#ff0000",
        'costPerOunce': 0.30
    }, 
    {
        name: 'Gala Apple',
        taste: "sweet",
        img: galaApple,
        calories: 16,
        totalFat: '0.03g',
        sodium: '0.28mg',
        totalCarbohydrate: '3.88g',
        sugar: '2.94g',
        protein: '0.07g',
        vitamins: {
            vitaminA: '0.28mcg',
            thiamin: '0.005mg',
            riboflavin: '0.008mg',
            niacin: "0.021mg",
            pantothenicAcid: '0.016mg',
            vitaminB6: '0.014mg',
            vitaminC: '0.0mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.05mg',
            vitaminK: '0.3mcg',
            betaine: '0.0mg',
            choline: '1.0mg',
            calcium: '1.98mg',
            iron: '0.03mg',
            copper: '0.006mg',
            magnesium: '1.42mg',
            manganese: '0.009mg',
            phosphorus: '3.69mg',
            potassium: '30.90mg',
            selenium: '0',
            zinc: '0.01mg'
        },
        'unit': 'micrograms',
        facts:["Great source of vitamin C.", "antioxidant and anti-inflammatory properties"],
        shortFacts: ["Source of stuff","Good for this and that, that, and this.", 'It taste good!'],
        "minerals": {
            magnesium: 0.06
        },
        'color': "#ff0000",
        'costPerOunce': 0.30
    },
    {
        name: 'Golden Delicious Apple',
        img: goldenDeliciousApple,
        calories: 16,
        totalCarbohydrate: '3.86g',
        sugar: '2.85g',
        totalFat: '0.04g',
        vitamins: {
            vitaminA: '0.85mcg',
            thiamin: '0.005mg',
            riboflavin: '0.007mg',
            niacin: "0.027mg",
            pantothenicAcid: '0.021mg',
            vitaminB6: '0.014mg',
            vitaminC: '0.0mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.05mg',
            vitaminK: '0.5mcg',
            betaine: '0.0mg',
            choline: '1.4mg',
            calcium: '1.70mg',
            copper: '0.009mg',
            iron: '0.04mg',
            magnesium: '1.42mg',
            manganese: '0.010mg',
            phosphorus: '2.83mg',
            potassium: '28.35mg',
            selenium: '0',
            sodium: "0.57mg",
            zinc: '0.01mg'
        },
        protein: '0.08g',
        facts:[ "antioxidant and anti-inflammatory properties"],
        shortFacts: ["Source of stuff","Good for this and that, that, and this.", 'It taste good!'],
        'color': "#000000",
        'costPerOunce': 0
    },
    {
        'name': 'Granny Smith Apple',
        taste: "tarty",
        img: grannySmithApple,
        calories: 12,
        totalCarbohydrate: 'g',
        sugar: 'g',
        totalFat: 'g',
        vitamins: {
            vitaminA: 'mcg',
            thiamin: 'mg',
            riboflavin: 'mg',
            niacin: "mg",
            pantothenicAcid: 'mg',
            vitaminB6: 'mg',
            vitaminC: '0.0mg',
            vitaminD: '0.0mcg',
            vitaminE: 'mg',
            vitaminK: 'mcg',
            betaine: '0.0mg',
            choline: 'mg',
            calcium: 'mg',
            copper: 'mg',
            iron: 'mg',
            magnesium: 'mg',
            manganese: 'mg',
            phosphorus: 'mg',
            potassium: 'mg',
            selenium: '',
            sodium: "mg",
            zinc: 'mg'
        },
        protein: 'g',
        facts:[""],
        shortFacts: [""],
        'color': "#000000",
        'costPerOunce': 0
    },
    {
        name: 'Red Delicious Apple',
        img: redDeliciousApple,
        calories: 17,
        totalCarbohydrate: '3.99g',
        sugar: '2.97g',
        totalFat: 'g',
        vitamins: {
            vitaminA: '0.85mcg',
            thiamin: '0.004mg',
            riboflavin: '0.007mg',
            niacin: "0.021mg",
            pantothenicAcid: '0.014mg',
            vitaminB6: '0.010mg',
            vitaminC: '0.0mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.07mg',
            vitaminK: '0.7mcg',     
            betaine: '0.0mg',
            choline: '1.0mg',
            calcium: '1.70mg',
            copper: '0.008mg',
            iron: '0.03mg',
            magnesium: '1.42mg',
            manganese: '0.010mg',
            phosphorus: '3.40mg',
            potassium: '29.48mg',
            selenium: '0.0mg',
            sodium: "0.28mg",
            zinc: '0.01mg'
        },
        protein: '0.08g',
        facts:[""],
        shortFacts: [""],
        'color': "#000000",
        'costPerOunce': 0
    },
    {
        'name': 'Beets',
        img: beets,
        calories: 12,
        totalCarbohydrate: '2.71g',
        sugar: '1.92g',
        totalFat: '0.05g',
        vitamins: {
            vitaminA: '0.57mcg',
            thiamin: '0.009mg',
            riboflavin: '0.011mg',
            niacin: "0.095mg",
            pantothenicAcid: '0.044mg',
            vitaminB6: '0.019mg',
            vitaminC: '1.4mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.01mg',
            vitaminK: '0.1mcg',
            betaine: '36.5mg',
            choline: '1.7mg',
            calcium: '4.54mg',
            copper: '0.021mg',
            iron: '0.23mg',
            magnesium: '6.52mg',
            manganese: '0.093mg',
            phosphorus: '11.34mg',
            potassium: '92.14mg',
            selenium: '0.2mcg',
            sodium: "22.11mg",
            zinc: '0.10mg'
        },
        protein: '0.46g',
        facts:[""],
        shortFacts: [""],
        'color': "#000000",
        'costPerOunce': 0
    },
    {
        'name': 'Broccoli',
        img: broccoli,
        calories: 9.6,
        totalCarbohydrate: '1.88g',
        sugar: '0.48g',
        totalFat: '0.10g',
        vitamins: {
            vitaminA: '8.79mcg',
            thiamin: '0.020mg',
            riboflavin: '0.033mg',
            niacin: "0.181mg",
            pantothenicAcid: '0.162mg',
            vitaminB6: '0.050mg',
            vitaminB12: "0.0mcg",
            vitaminC: '25.3mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.22mg',
            vitaminK: '28.8mcg',
            betaine: '0.0mg',
            choline: '5.3mg',
            calcium: '13.32mg',
            copper: '0.014mg',
            iron: '0.21mg',
            magnesium: '5.95mg',
            manganese: '0.060mg',
            phosphorus: '18.71mg',
            potassium: '89.58mg',
            selenium: '0.7mcg',
            sodium: "9.36mg",
            zinc: '0.12mg'
        },
        protein: '0.80g',
        facts:[""],
        shortFacts: [""],
        'color': "#000000",
        'costPerOunce': 0
    },
    {
        'name': 'Cantaloupe',
        img: cantaloupe,
        calories: 9.6,
        totalCarbohydrate: '2.31g',
        sugar: '2.23g',
        totalFat: '0.05g',
        vitamins: {
            vitaminA: '47.91mcg',
            thiamin: '0.012mg',
            riboflavin: '0.005mg',
            niacin: "0.208mg",
            pantothenicAcid: '0.030mg',
            vitaminB6: '0.020mg',
            vitaminB12: "0.0mcg",
            vitaminC: '10.4mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.01mg',
            vitaminK: '0.7mcg',
            betaine: '0.0mg',
            choline: '2.2mg',
            calcium: '2.55mg',
            copper: '0.012mg',
            iron: '0.06mg',
            magnesium: '3.40mg',
            manganese: '0.012mg',
            phosphorus: '4.25mg',
            potassium: '75.69mg',
            selenium: '0.1mcg',
            sodium: "4.54mg",
            zinc: '0.05mg'
        },
        protein: '0.24g',
        facts:[""],
        shortFacts: [""],
        'color': "#000000",
        'costPerOunce': 0
    },
    {
        'name': 'Carrot',
        img: carrots,
        calories: 12,
        totalCarbohydrate: '2.72g',
        sugar: '1.34g',
        totalFat: '0.07g',
        vitamins: {
            vitaminA: '236.72mcg',
            thiamin: '0.019mg',
            riboflavin: '0.016mg',
            niacin: "0.279mg",
            pantothenicAcid: '0.077mg',
            vitaminB6: '0.039mg',
            vitaminB12: "0.0mcg",
            vitaminC: '1.7mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.19mg',
            vitaminK: '3.7mcg',
            betaine: '0.1mg',
            choline: '2.5mg',
            calcium: '9.36mg',
            copper: '0.013mg',
            fluoride: "0.9mcg",
            iron: '0.09mg',
            magnesium: '3.40mg',
            manganese: '0.041mg',
            phosphorus: '9.92mg',
            potassium: '90.72mg',
            selenium: '0.0mcg',
            sodium: "19.56mg",
            zinc: '0.07mg'
        },
        protein: '0.26g',
        facts:[""],
        shortFacts: [""],
        'color': "#000000",
        'costPerOunce': 0
    },
    {
        'name': 'Celery',
        img: celery,
        calories: 4,
        totalCarbohydrate: '0.84g',
        sugar: '0.38g',
        totalFat: '0.05g',
        vitamins: {
            vitaminA: '6.24mcg',
            thiamin: '0.006mg',
            riboflavin: '0.016mg',
            niacin: "0.091mg",
            pantothenicAcid: '0.070mg',
            vitaminB6: '0.021mg',
            vitaminB12: "0.0mcg",
            vitaminC: '0.9mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.08mg',
            vitaminK: '8.3mcg',
            betaine: '0.0mg',
            choline: '1.7mg',
            calcium: '11.34mg',
            copper: '0.010mg',
            fluoride: "1.1mcg",
            iron: '0.06mg',
            magnesium: '3.12mg',
            manganese: '0.029mg',
            phosphorus: '6.80mg',
            potassium: '73.71mg',
            selenium: '0.1mcg',
            sodium: "22.68mg",
            zinc: '0.04mg'
        },
        protein: '0.20g',
        facts:[""],
        shortFacts: [""],
        'color': "#000000",
        'costPerOunce': 0
    },
    {
        'name': 'Cucumber',
        img: cucumber,
        calories: 4.3,
        totalCarbohydrate: '1.03g',
        sugar: '0.47g',
        totalFat: '0.03g',
        vitamins: {
            vitaminA: '1.42mcg',
            thiamin: '0.008mg',
            riboflavin: '0.009mg',
            niacin: "0.028mg",
            pantothenicAcid: '0.0mg',
            vitaminB6: '0.011mg',
            vitaminB12: "0.0mcg",
            vitaminC: '0.8mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.01mg',
            vitaminK: '4.6mcg',
            betaine: '0.0mg',
            choline: '1.7mg',
            calcium: '4.54mg',
            copper: '0.012mg',
            fluoride: "0.0mcg",
            iron: '0.08mg',
            magnesium: '3.69mg',
            manganese: '0.0mg',
            phosphorus: '6.80mg',
            potassium: '41.67mg',
            selenium: '0.1mcg',
            sodium: "0.57mg",
            zinc: '0.06mg'
        },
        protein: '0.18g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Ginger',
        img: ginger,
        calories: 23,
        totalCarbohydrate: '5.04g',
        sugar: '0.48g',
        totalFat: '0.21g',
        vitamins: {
            vitaminA: '0.0mcg',
            thiamin: '0.007mg',
            riboflavin: '0.010mg',
            niacin: "0.213mg",
            pantothenicAcid: '0.058mg',
            vitaminB6: '0.045mg',
            vitaminB12: "0.0mcg",
            vitaminC: '1.4mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.07mg',
            vitaminK: '0.0mcg',
            betaine: '0.0mg',
            choline: '8.2mg',
            calcium: '4.54mg',
            copper: '0.64mg',
            fluoride: "0.0mcg",
            iron: '0.17mg',
            magnesium: '12.19mg',
            manganese: '0.065mg',
            phosphorus: '9.64mg',
            potassium: '117.65mg',
            selenium: '0.2mcg',
            sodium: "3.69mg",
            zinc: '0.10mg'
        },
        protein: '0.52g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Green Grapes',
        img: greenGrapes,
        calories: 20,
        totalCarbohydrate: '5.13g',
        sugar: '4.39g',
        totalFat: '0.05g',
        vitamins: {
            vitaminA: '0.85mcg',
            thiamin: '0.020mg',
            riboflavin: '0.020mg',
            niacin: "0.053mg",
            pantothenicAcid: '0.0mg',
            vitaminB6: '0.024mg',
            vitaminB12: "0.0mcg",
            vitaminC: '0.9mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.05mg',
            vitaminK: '4.1mcg',
            betaine: '0.0mg',
            choline: '1.6mg',
            calcium: '2.83mg',
            copper: '0.036mg',
            fluoride: "0.0mcg",
            iron: '0.10mg',
            magnesium: '1.98mg',
            manganese: '0.0mg',
            phosphorus: '5.67mg',
            potassium: '54.15mg',
            selenium: '0.0mcg',
            sodium: "0.57mg",
            zinc: '0.02mg'
        },
        protein: '0.20g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Red Grapes',
        calories: 20,
        totalCarbohydrate: '5.13g',
        sugar: '4.39g',
        totalFat: '0.05g',
        vitamins: {
            vitaminA: '0.85mcg',
            thiamin: '0.020mg',
            riboflavin: '0.020mg',
            niacin: "0.053mg",
            pantothenicAcid: '0.0mg',
            vitaminB6: '0.024mg',
            vitaminB12: "0.0mcg",
            vitaminC: '0.9mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.05mg',
            vitaminK: '4.1mcg',
            betaine: '0.0mg',
            choline: '1.6mg',
            calcium: '2.83mg',
            copper: '0.036mg',
            fluoride: "0.0mcg",
            iron: '0.10mg',
            magnesium: '1.98mg',
            manganese: '0.0mg',
            phosphorus: '5.67mg',
            potassium: '54.15mg',
            selenium: '0.0mcg',
            sodium: "0.57mg",
            zinc: '0.02mg'
        },
        protein: '0.20g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Black Grapes',
        img: blackGrapes,
        calories: 20,
        totalCarbohydrate: '5.13g',
        sugar: '4.39g',
        totalFat: '0.05g',
        vitamins: {
            vitaminA: '0.85mcg',
            thiamin: '0.020mg',
            riboflavin: '0.020mg',
            niacin: "0.053mg",
            pantothenicAcid: '0.0mg',
            vitaminB6: '0.024mg',
            vitaminB12: "0.0mcg",
            vitaminC: '0.9mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.05mg',
            vitaminK: '4.1mcg',
            betaine: '0.0mg',
            choline: '1.6mg',
            calcium: '2.83mg',
            copper: '0.036mg',
            fluoride: "0.0mcg",
            iron: '0.10mg',
            magnesium: '1.98mg',
            manganese: '0.0mg',
            phosphorus: '5.67mg',
            potassium: '54.15mg',
            selenium: '0.0mcg',
            sodium: "0.57mg",
            zinc: '0.02mg'
        },
        protein: '0.20g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Grapefruit',
        img: grapefruit,
        calories: 12,
        totalCarbohydrate: '3.02g',
        sugar: '1.95g',
        totalFat: '0.05g',
        vitamins: {
            vitaminA: '16.44mcg',
            thiamin: '0.012mg',
            riboflavin: '0.009mg',
            niacin: "0.058mg",
            pantothenicAcid: '0.0mg',
            vitaminB6: '0.015mg',
            vitaminB12: "0.0mcg",
            vitaminC: '8.8mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.04mg',
            vitaminK: '0.0mcg',
            betaine: '0.0mg',
            choline: '2.2mg',
            calcium: '6.24mg',
            copper: '0.009mg',
            fluoride: "0.0mcg",
            iron: '0.02mg',
            magnesium: '2.55mg',
            manganese: '0.0mg',
            phosphorus: '5.10mg',
            potassium: '38.27mg',
            selenium: '0.0mcg',
            sodium: "0.0mg",
            zinc: '0.02mg'
        },
        protein: '0.22g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Honeydew Melon',
        img: honeydew,
        calories: 10,
        totalCarbohydrate: '2.58g',
        sugar: '2.30g',
        totalFat: '0.04g',
        vitamins: {
            vitaminA: '0.85mcg',
            thiamin: '0.011mg',
            riboflavin: '0.003mg',
            niacin: "0.119mg",
            pantothenicAcid: '0.0mg',
            vitaminB6: '0.025mg',
            vitaminB12: "0.0mcg",
            vitaminC: '5.1mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.01mg',
            vitaminK: '0.8mcg',
            betaine: '0.0mg',
            choline: '2.2mg',
            calcium: '1.70mg',
            copper: '0.007mg',
            fluoride: "0.0mcg",
            iron: '0.05mg',
            magnesium: '2.83mg',
            manganese: '0.0mg',
            phosphorus: '3.12mg',
            potassium: '64.64mg',
            selenium: '0.2mcg',
            sodium: "5.10mg",
            zinc: '0.03mg'
        },
        protein: '0.15g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Kale',
        img: kale,
        calories: 9.9,
        totalCarbohydrate: '1.25g',
        sugar: '0.28g',
        totalFat: '0.42g',
        vitamins: {
            vitaminA: '68.32mcg',
            thiamin: '0.032mg',
            riboflavin: '0.098mg',
            niacin: "0.335mg",
            pantothenicAcid: '0.105mg',
            vitaminB6: '0.042mg',
            folate: '17.58mcg',
            vitaminB12: "0.0mcg",
            vitaminC: '26.5mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.19mg',
            vitaminK: '110.4mcg',
            betaine: '0.1mg',
            choline: '0.1mg',
            calcium: '72.01mg',
            copper: '0.015mg',
            fluoride: "0.0mcg",
            iron: '0.45mg',
            magnesium: '9.36mg',
            manganese: '0.261mg',
            phosphorus: '15.59mg',
            potassium: '98.66mg',
            selenium: '0.3mcg',
            sodium: "15.03mg",
            zinc: '0.11mg'
        },
        protein: '0.83g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Kiwi',
        img: kiwi,
        calories: 16,
        totalCarbohydrate: '3.97g',
        sugar: '2.55g',
        totalFat: '0.12g',
        vitamins: {
            vitaminA: '1.13mcg',
            thiamin: '0.008mg',
            riboflavin: '0.007mg',
            niacin: "0.105mg",
            pantothenicAcid: '0.0mg',
            vitaminB6: '0.017mg',
            folate: '7.37mcg',
            vitaminB12: "0.0mcg",
            vitaminC: '21.2mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.37mg',
            vitaminK: '11.4mcg',
            betaine: '0.0mg',
            choline: '2.2mg',
            calcium: '9.92mg',
            copper: '0.038mg',
            fluoride: "0.0mcg",
            iron: '0.07mg',
            magnesium: '4.54mg',
            manganese: '0.0mg',
            phosphorus: '9.64mg',
            potassium: '56.13mg',
            selenium: '0.1mcg',
            sodium: "1.42mg",
            zinc: '0.04mg'
        },
        protein: '0.30g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Lemons',
        img: lemons,
        calories: 8.2,
        totalCarbohydrate: '2.64g',
        sugar: '0.71g',
        totalFat: '0.09g',
        vitamins: {
            vitaminA: '0.28mcg',
            thiamin: '0.011mg',
            riboflavin: '0.006mg',
            niacin: "0.028mg",
            pantothenicAcid: '0.0mg',
            vitaminB6: '0.023mg',
            folate: "3.12mcg",
            vitaminB12: "0.0mcg",
            vitaminC: '15..0mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.04mg',
            vitaminK: '0.0mcg',
            betaine: '0.0mg',
            choline: '1.4mg',
            calcium: '7.37mg',
            copper: '0.010mg',
            fluoride: "0.0mcg",
            iron: '0.17mg',
            magnesium: '2.27mg',
            manganese: '0.0mg',
            phosphorus: '4.54mg',
            potassium: '39.12mg',
            selenium: '0.1mcg',
            sodium: "0.57mg",
            zinc: '0.02mg'
        },
        protein: '0.31g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Iceberg Lettuce',
        img: icebergLettuce,
        calories: 4,
        totalCarbohydrate: '0.84g',
        sugar: '0.56g',
        totalFat: '0.04g',
        vitamins: {
            vitaminA: '7.09mcg',
            thiamin: '0.012mg',
            riboflavin: '0.007mg',
            niacin: "0.035mg",
            pantothenicAcid: '0.026mg',
            vitaminB6: '0.012mg',
            floate: '8.22mcg',
            vitaminB12: "0.0mcg",
            vitaminC: '0.8mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.05mg',
            vitaminK: '6.8mcg',
            betaine: '0.0mg',
            choline: '1.9mg',
            calcium: '5.10mg',
            copper: '0.007mg',
            fluoride: "0.0mcg",
            iron: '0.12mg',
            magnesium: '1.98mg',
            manganese: '0.035mg',
            phosphorus: '5.67mg',
            potassium: '39.97mg',
            selenium: '0.0mcg',
            sodium: "2.83mg",
            zinc: '0.04mg'
        },
        protein: '0.26g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },

    {
        'name': 'Romaine Lettuce',
        img: romaineLettuce,
        calories: 4.3,
        totalCarbohydrate: '0.81g',
        sugar: '0.22g',
        totalFat: '0.04g',
        vitamins: {
            vitaminA: '104.89mcg',
            thiamin: '0.020mg',
            riboflavin: '0.023mg',
            niacin: "0.106mg",
            pantothenicAcid: '0.0mg',
            vitaminB6: '0.026mg',
            folate: '10.77mcg',
            vitaminB12: "0.0mcg",
            vitaminC: '2.6mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.06mg',
            vitaminK: '35.8mcg',
            betaine: '0.0mg',
            choline: '3.9mg',
            calcium: '10.21mg',
            copper: '0.008mg',
            fluoride: "0.0mcg",
            iron: '0.24mg',
            magnesium: '3.69mg',
            manganese: '0.0mg',
            phosphorus: '8.22mg',
            potassium: '55.0mg',
            selenium: '0.2mcg',
            sodium: "7.94mg",
            zinc: '0.05mg'
        },
        protein: '0.39g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Lime',
        img: lime,
        calories: 8.5,
        totalCarbohydrate: '2.99g',
        sugar: '0.48g',
        totalFat: '0.06g',
        vitamins: {
            vitaminA: '0.57mcg',
            thiamin: '0.009mg',
            riboflavin: '0.006mg',
            niacin: "0.057mg",
            pantothenicAcid: '0.0mg',
            vitaminB6: '0.012mg',
            folate: "2.27mcg",
            vitaminB12: "0.0mcg",
            vitaminC: '8.2mg',
            vitaminD: '0.0mcg',
            vitaminE: '0.06mg',
            vitaminK: '0.2mcg',
            betaine: '0.0mg',
            choline: '1.4mg',
            calcium: '9.36mg',
            copper: '0.018mg',
            fluoride: "0.0mcg",
            iron: '0.17mg',
            magnesium: 'mg',
            manganese: 'mg',
            phosphorus: 'mg',
            potassium: 'mg',
            selenium: 'mcg',
            sodium: "mg",
            zinc: 'mg'
        },
        protein: 'g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Oranges',
        img: oranges, calories: 12,
        totalCarbohydrate: 'g',
        sugar: 'g',
        totalFat: 'g',
        vitamins: {
            vitaminA: 'mcg',
            thiamin: 'mg',
            riboflavin: 'mg',
            niacin: "mg",
            pantothenicAcid: 'mg',
            vitaminB6: 'mg',
            vitaminB12: "mcg",
            vitaminC: 'mg',
            vitaminD: 'mcg',
            vitaminE: 'mg',
            vitaminK: 'mcg',
            betaine: 'mg',
            choline: 'mg',
            calcium: 'mg',
            copper: 'mg',
            fluoride: "mcg",
            iron: 'mg',
            magnesium: 'mg',
            manganese: 'mg',
            phosphorus: 'mg',
            potassium: 'mg',
            selenium: 'mcg',
            sodium: "mg",
            zinc: 'mg'
        },
        protein: 'g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Parsley',
        img: parsley, calories: 12,
        totalCarbohydrate: 'g',
        sugar: 'g',
        totalFat: 'g',
        vitamins: {
            vitaminA: 'mcg',
            thiamin: 'mg',
            riboflavin: 'mg',
            niacin: "mg",
            pantothenicAcid: 'mg',
            vitaminB6: 'mg',
            vitaminB12: "mcg",
            vitaminC: 'mg',
            vitaminD: 'mcg',
            vitaminE: 'mg',
            vitaminK: 'mcg',
            betaine: 'mg',
            choline: 'mg',
            calcium: 'mg',
            copper: 'mg',
            fluoride: "mcg",
            iron: 'mg',
            magnesium: 'mg',
            manganese: 'mg',
            phosphorus: 'mg',
            potassium: 'mg',
            selenium: 'mcg',
            sodium: "mg",
            zinc: 'mg'
        },
        protein: 'g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Pineapple',
        img: peaches, calories: 12,
        totalCarbohydrate: 'g',
        sugar: 'g',
        totalFat: 'g',
        vitamins: {
            vitaminA: 'mcg',
            thiamin: 'mg',
            riboflavin: 'mg',
            niacin: "mg",
            pantothenicAcid: 'mg',
            vitaminB6: 'mg',
            vitaminB12: "mcg",
            vitaminC: 'mg',
            vitaminD: 'mcg',
            vitaminE: 'mg',
            vitaminK: 'mcg',
            betaine: 'mg',
            choline: 'mg',
            calcium: 'mg',
            copper: 'mg',
            fluoride: "mcg",
            iron: 'mg',
            magnesium: 'mg',
            manganese: 'mg',
            phosphorus: 'mg',
            potassium: 'mg',
            selenium: 'mcg',
            sodium: "mg",
            zinc: 'mg'
        },
        protein: 'g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Peaches',
        img: peaches, calories: 12,
        totalCarbohydrate: 'g',
        sugar: 'g',
        totalFat: 'g',
        vitamins: {
            vitaminA: 'mcg',
            thiamin: 'mg',
            riboflavin: 'mg',
            niacin: "mg",
            pantothenicAcid: 'mg',
            vitaminB6: 'mg',
            vitaminB12: "mcg",
            vitaminC: 'mg',
            vitaminD: 'mcg',
            vitaminE: 'mg',
            vitaminK: 'mcg',
            betaine: 'mg',
            choline: 'mg',
            calcium: 'mg',
            copper: 'mg',
            fluoride: "mcg",
            iron: 'mg',
            magnesium: 'mg',
            manganese: 'mg',
            phosphorus: 'mg',
            potassium: 'mg',
            selenium: 'mcg',
            sodium: "mg",
            zinc: 'mg'
        },
        protein: 'g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Pears',
        img: pears, calories: 12,
        totalCarbohydrate: 'g',
        sugar: 'g',
        totalFat: 'g',
        vitamins: {
            vitaminA: 'mcg',
            thiamin: 'mg',
            riboflavin: 'mg',
            niacin: "mg",
            pantothenicAcid: 'mg',
            vitaminB6: 'mg',
            vitaminB12: "mcg",
            vitaminC: 'mg',
            vitaminD: 'mcg',
            vitaminE: 'mg',
            vitaminK: 'mcg',
            betaine: 'mg',
            choline: 'mg',
            calcium: 'mg',
            copper: 'mg',
            fluoride: "mcg",
            iron: 'mg',
            magnesium: 'mg',
            manganese: 'mg',
            phosphorus: 'mg',
            potassium: 'mg',
            selenium: 'mcg',
            sodium: "mg",
            zinc: 'mg'
        },
        protein: 'g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Strawberries',
        img: strawberries, calories: 12,
        totalCarbohydrate: 'g',
        sugar: 'g',
        totalFat: 'g',
        vitamins: {
            vitaminA: 'mcg',
            thiamin: 'mg',
            riboflavin: 'mg',
            niacin: "mg",
            pantothenicAcid: 'mg',
            vitaminB6: 'mg',
            vitaminB12: "mcg",
            vitaminC: 'mg',
            vitaminD: 'mcg',
            vitaminE: 'mg',
            vitaminK: 'mcg',
            betaine: 'mg',
            choline: 'mg',
            calcium: 'mg',
            copper: 'mg',
            fluoride: "mcg",
            iron: 'mg',
            magnesium: 'mg',
            manganese: 'mg',
            phosphorus: 'mg',
            potassium: 'mg',
            selenium: 'mcg',
            sodium: "mg",
            zinc: 'mg'
        },
        protein: 'g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Tomatoes',
        img: tomatoes, calories: 12,
        totalCarbohydrate: 'g',
        sugar: 'g',
        totalFat: 'g',
        vitamins: {
            vitaminA: 'mcg',
            thiamin: 'mg',
            riboflavin: 'mg',
            niacin: "mg",
            pantothenicAcid: 'mg',
            vitaminB6: 'mg',
            vitaminB12: "mcg",
            vitaminC: 'mg',
            vitaminD: 'mcg',
            vitaminE: 'mg',
            vitaminK: 'mcg',
            betaine: 'mg',
            choline: 'mg',
            calcium: 'mg',
            copper: 'mg',
            fluoride: "mcg",
            iron: 'mg',
            magnesium: 'mg',
            manganese: 'mg',
            phosphorus: 'mg',
            potassium: 'mg',
            selenium: 'mcg',
            sodium: "mg",
            zinc: 'mg'
        },
        protein: 'g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': "Turmeric",
        img: turmeric, calories: 12,
        totalCarbohydrate: 'g',
        sugar: 'g',
        totalFat: 'g',
        vitamins: {
            vitaminA: 'mcg',
            thiamin: 'mg',
            riboflavin: 'mg',
            niacin: "mg",
            pantothenicAcid: 'mg',
            vitaminB6: 'mg',
            vitaminB12: "mcg",
            vitaminC: 'mg',
            vitaminD: 'mcg',
            vitaminE: 'mg',
            vitaminK: 'mcg',
            betaine: 'mg',
            choline: 'mg',
            calcium: 'mg',
            copper: 'mg',
            fluoride: "mcg",
            iron: 'mg',
            magnesium: 'mg',
            manganese: 'mg',
            phosphorus: 'mg',
            potassium: 'mg',
            selenium: 'mcg',
            sodium: "mg",
            zinc: 'mg'
        },
        protein: 'g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
    {
        'name': 'Watermelon',
        img: watermelon,
        calories: 12,
        totalCarbohydrate: 'g',
        sugar: 'g',
        totalFat: 'g',
        vitamins: {
            vitaminA: 'mcg',
            thiamin: 'mg',
            riboflavin: 'mg',
            niacin: "mg",
            pantothenicAcid: 'mg',
            vitaminB6: 'mg',
            vitaminB12: "mcg",
            vitaminC: 'mg',
            vitaminD: 'mcg',
            vitaminE: 'mg',
            vitaminK: 'mcg',
            betaine: 'mg',
            choline: 'mg',
            calcium: 'mg',
            copper: 'mg',
            fluoride: "mcg",
            iron: 'mg',
            magnesium: 'mg',
            manganese: 'mg',
            phosphorus: 'mg',
            potassium: 'mg',
            selenium: 'mcg',
            sodium: "mg",
            zinc: 'mg'
        },
        protein: 'g',
        facts:[""],
        shortFacts: [""],
        color: "#000000",
        costPerOunce: 0
    },
];


export default list;
