
import grannySmithApple from "./assets/granny-smith-apple.jpg";
import redDeliciousApple from "./assets/red-delicious-apple.jpg";
import beets from "./assets/beetss.png";
import cantaloupe from "./assets/cantaloupe.jpg";
import carrots from "./assets/carrots.jpg";
import celery from "./assets/celery.jpg";
import cucumber from "./assets/cucumber.jpg";
import ginger from "./assets/ginger.jpg";
import greenGrapes from "./assets/green-grapes.jpg";
import redGrapes from "./assets/red-grapes.jpg";
import grapefruit from "./assets/grapefruit.jpg";
import honeydew from "./assets/honeydew.jpg";
import kale from "./assets/kale.jpg";
import kiwi from "./assets/kiwi.jpg";
import lemons from "./assets/lemons.jpg";
import lime from "./assets/lime.jpg";
import mango from './assets/mango.jpg'
import oranges from "./assets/oranges.jpg";
import pineapple from "./assets/pineapple.jpg";
import peaches from "./assets/peaches.jpg";
import pears from "./assets/pears.jpg";
import strawberries from "./assets/strawberries.jpg";
import watermelon from "./assets/watermelon.jpg";

export const minerals = {
  vitaminA: "Vitamin A",
  vitaminB6: "Vitamin B6",
  vitaminB12: "Vitamin B12",
  vitaminC: "Vitamin C",
  vitaminD: "Vitamin D",
  vitaminE: "Vitamin E",
  vitaminK: "Vitamin K",
  biotin: "Biotin",
  calcium: "Calcium",
  chloride: "Chloride",
  choline: "Choline",
  chromium: "Chromium",
  cholesterol: "Cholesterol",
  copper: "Copper",
  vitaminB6: "vitamin B6",
  vitaminB9: "vitamin B9",
  iodine: "Iodine",
  iron: "Iron",
  magnesium: "Magnesium",
  manganese: "Manganese",
  molybdenum: "Molybdenum",
  vitaminB3: "vitaminB3",
  vitaminB5: "Pantothenic Acid",
  phosphorus: "Phosphorus",
  potassium: "Potassium",
  protein: "Protein",
  vitaminB2: "Vitamin B2",
  saturatedFat: "Saturated Fat",
  selenium: "Selenium",
  sodium: "Sodium",
  vitaminB1: "Vitamin B1",
  totalCarbohydrate: "Total Carbohydrate",
  totalFat: "Total Fat",
  zinc: "Zinc",
};

//const list = [data];
export const dailyRecommendation = {
  vitaminA: ".900mg",
  vitaminB6: "1.7mg",
  vitaminB9: ".400mg",
  vitaminB12: "0.0024mg",
  vitaminC: "90mg",
  vitaminD: "0.020mg",
  vitaminE: "15mg",
  vitaminK: "0.120mg",
  biotin: "0.030mg",
  calcium: "1300mg",
  chloride: "2300mg",
  choline: "550mg",
  chromium: "0.035mg",
  cholesterol: "300mg",
  copper: "0.9mg",
  vitaminB6: "0.400mg",
  iodine: "0.150mg",
  iron: "18mg",
  magnesium: "420mg",
  manganese: "2.3mg",
  vitaminB3: "16mg",
  vitaminB5: "5mg",
  phosphorus: "1250mg",
  potassium: "4700mg",
  protein: "50g",
  vitaminB2: "1.3mg",
  saturatedFat: "20g",
  selenium: "0.055mg",
  sodium: "2300mg",
  vitaminB1: "1.2mg",
  totalCarbohydrate: "275g",
  totalFat: "78g",
  zinc: "11mg",
};

export const listt = {

  "Granny Smith Apple": {
    calories: 16,
    totalCarbohydrate: "3.9g",
    sugar: "2.9g",
    totalFat: "0g",
    vitaminA: "0.00085mg",
    vitaminB1: "0.005mg",
    vitaminB2: "0.007mg",
    vitaminB3: "0.027mg",
    vitaminB5: "0.021mg",
    vitaminB6: "0.014mg",
    vitaminB9: "0mg",
    vitaminC: "0.0mg",
    vitaminD: "0.0mg",
    vitaminE: "0.05mg",
    vitaminK: "0.0005mg",
    betaine: "0.0mg",
    choline: "1.4mg",
    calcium: "1.70mg",
    copper: "0.01mg",
    iron: "0.04mg",
    magnesium: "1.42mg",
    manganese: "0.01mg",
    phosphorus: "2.83mg",
    potassium: "28.35mg",
    selenium: "0.0mg",
    sodium: "0.57mg",
    zinc: "0.01mg",
    protein: "0.08g"
  },
  "Red Delicious Apple": {
    calories: 18,
    totalCarbohydrate: "4.2g",
    sugar: "2.97g",
    totalFat: "0.1g",
    vitaminA: "0.0mg",
    vitaminB1: "0.003mg",
    vitaminB2: "0.019mg",
    vitaminB3: "0.026mg",
    vitaminB5: "0.014mg",
    vitaminB6: "0.010mg",
    vitaminB9: "0.00mg",
    vitaminB12: "0mg",
    vitaminC: "0.0mg",
    vitaminD: "0.0mg",
    vitaminE: "0.07mg",
    vitaminK: "0.0007mg",
    betaine: "0.0mg",
    choline: "1.0mg",
    calcium: "1.42mg",
    copper: "0.01mg",
    iron: "0.00mg",
    magnesium: "1.33mg",
    manganese: "0.009mg",
    phosphorus: "2.55mg",
    potassium: "26.93mg",
    selenium: "0.0mg",
    sodium: "0.00mg",
    zinc: "0.01mg",
    protein: "0.05g"
  },
  Beets: {
    calories: 12,
    totalCarbohydrate: "2.71g",
    sugar: "1.92g",
    totalFat: "0.05g",
    vitaminA: "0.00057mg",
    vitaminB1: "0.009mg",
    vitaminB2: "0.011mg",
    vitaminB3: "0.095mg",
    vitaminB5: "0.044mg",
    vitaminB6: "0.019mg",
    vitaminB9: "0.0309mg",
    vitaminB12: "0mg",
    vitaminC: "1.4mg",
    vitaminD: "0.0mg",
    vitaminE: "0.01mg",
    vitaminK: "0.0001mg",
    betaine: "36.5mg",
    choline: "1.7mg",
    calcium: "4.54mg",
    copper: "0.021mg",
    iron: "0.23mg",
    magnesium: "6.52mg",
    manganese: "0.093mg",
    phosphorus: "11.34mg",
    potassium: "92.14mg",
    selenium: "0.2mg",
    sodium: "22.11mg",
    zinc: "0.10mg",
    protein: "0.46g"
  },
  Cantaloupe: {
    calories: 9.6,
    totalCarbohydrate: "2.31g",
    sugar: "2.23g",
    totalFat: "0.05g",
    vitaminA: "0.04791mg",
    vitaminB1: "0.012mg",
    vitaminB2: "0.005mg",
    vitaminB3: "0.208mg",
    vitaminB5: "0.030mg",
    vitaminB6: "0.020mg",
    vitaminB9: "0.00397mg",
    vitaminB12: "0.0mg",
    vitaminC: "10.4mg",
    vitaminD: "0.0mg",
    vitaminE: "0.01mg",
    vitaminK: "0.0007mg",
    betaine: "0.0mg",
    choline: "2.2mg",
    calcium: "2.55mg",
    copper: "0.012mg",
    iron: "0.06mg",
    magnesium: "3.40mg",
    manganese: "0.012mg",
    phosphorus: "4.25mg",
    potassium: "75.69mg",
    selenium: "0.0001mg",
    sodium: "4.54mg",
    zinc: "0.05mg",
    protein: "0.24g"
  },
  Carrot: {
    calories: 12,
    totalCarbohydrate: "2.72g",
    sugar: "1.34g",
    totalFat: "0.07g",
    vitaminA: "0.23672mg",
    vitaminB1: "0.019mg",
    vitaminB2: "0.016mg",
    vitaminB3: "0.279mg",
    vitaminB5: "0.077mg",
    vitaminB6: "0.039mg",
    vitaminB9: "0.00539mg",
    vitaminB12: "0.0mg",
    vitaminC: "1.7mg",
    vitaminD: "0.0mg",
    vitaminE: "0.19mg",
    vitaminK: "0.0037mg",
    betaine: "0.1mg",
    choline: "2.5mg",
    calcium: "9.36mg",
    copper: "0.013mg",
    fluoride: "0.0009mg",
    iron: "0.09mg",
    magnesium: "3.40mg",
    manganese: "0.041mg",
    phosphorus: "9.92mg",
    potassium: "90.72mg",
    selenium: "0.0mg",
    sodium: "19.56mg",
    zinc: "0.07mg",
    protein: "0.26g"
  },
  Celery: {
    calories: 4,
    totalCarbohydrate: "0.84g",
    sugar: "0.38g",
    totalFat: "0.05g",
    vitaminA: "0.00624mg",
    vitaminB1: "0.006mg",
    vitaminB2: "0.016mg",
    vitaminB3: "0.091mg",
    vitaminB5: "0.070mg",
    vitaminB6: "0.021mg",
    vitaminB9: "0.01021mg",
    vitaminB12: "0.0mg",
    vitaminC: "0.9mg",
    vitaminD: "0.0mg",
    vitaminE: "0.08mg",
    vitaminK: "0.0083mg",
    betaine: "0.0mg",
    choline: "1.7mg",
    calcium: "11.34mg",
    copper: "0.010mg",
    fluoride: "0.0011mg",
    iron: "0.06mg",
    magnesium: "3.12mg",
    manganese: "0.029mg",
    phosphorus: "6.80mg",
    potassium: "73.71mg",
    selenium: "0.0001mg",
    sodium: "22.68mg",
    zinc: "0.04mg",
    protein: "0.20g"
  },
  Cucumber: {
    calories: 4.3,
    totalCarbohydrate: "1.03g",
    sugar: "0.47g",
    totalFat: "0.03g",
    vitaminA: "0.00142mg",
    vitaminB1: "0.008mg",
    vitaminB2: "0.009mg",
    vitaminB3: "0.028mg",
    vitaminB5: "0.0mg",
    vitaminB6: "0.011mg",
    vitaminB9: "0.00198mg",
    vitaminB12: "0.0mg",
    vitaminC: "0.8mg",
    vitaminD: "0.0mg",
    vitaminE: "0.01mg",
    vitaminK: "0.0046mg",
    betaine: "0.0mg",
    choline: "1.7mg",
    calcium: "4.54mg",
    copper: "0.012mg",
    fluoride: "0.0mg",
    iron: "0.08mg",
    magnesium: "3.69mg",
    manganese: "0.0mg",
    phosphorus: "6.80mg",
    potassium: "41.67mg",
    selenium: "0.0001mg",
    sodium: "0.57mg",
    zinc: "0.06mg",
    protein: "0.18g"
  },
  Ginger: {
    calories: 23,
    totalCarbohydrate: "5.04g",
    sugar: "0.48g",
    totalFat: "0.21g",
    vitaminA: "0.0mg",
    vitaminB1: "0.007mg",
    vitaminB2: "0.010mg",
    vitaminB3: "0.213mg",
    vitaminB5: "0.058mg",
    vitaminB6: "0.045mg",
    vitaminB9: "0.00312mg",
    vitaminB12: "0.0mg",
    vitaminC: "1.4mg",
    vitaminD: "0.0mg",
    vitaminE: "0.07mg",
    vitaminK: "0.0mg",
    betaine: "0.0mg",
    choline: "8.2mg",
    calcium: "4.54mg",
    copper: "0.64mg",
    fluoride: "0.0mg",
    iron: "0.17mg",
    magnesium: "12.19mg",
    manganese: "0.065mg",
    phosphorus: "9.64mg",
    potassium: "117.65mg",
    selenium: "0.0002mg",
    sodium: "3.69mg",
    zinc: "0.10mg",
    protein: "0.52g"
  },
  "Green Grapes": {
    calories: 20,
    totalCarbohydrate: "5.13g",
    sugar: "4.39g",
    totalFat: "0.05g",
    vitaminA: "0.00085mg",
    vitaminB1: "0.020mg",
    vitaminB2: "0.020mg",
    vitaminB3: "0.053mg",
    vitaminB5: "0.0mg",
    vitaminB6: "0.024mg",
    vitaminB9: "0.00057mg",
    vitaminB12: "0.0mg",
    vitaminC: "0.9mg",
    vitaminD: "0.0mg",
    vitaminE: "0.05mg",
    vitaminK: "0.0041mg",
    betaine: "0.0mg",
    choline: "1.6mg",
    calcium: "2.83mg",
    copper: "0.036mg",
    fluoride: "0.0mg",
    iron: "0.10mg",
    magnesium: "1.98mg",
    manganese: "0.0mg",
    phosphorus: "5.67mg",
    potassium: "54.15mg",
    selenium: "0.0mg",
    sodium: "0.57mg",
    zinc: "0.02mg",
    protein: "0.20g"
  },
  "Red Grapes": {
    calories: 20,
    totalCarbohydrate: "5.13g",
    sugar: "4.39g",
    totalFat: "0.05g",
    vitaminA: "0.00085mg",
    vitaminB1: "0.020mg",
    vitaminB2: "0.020mg",
    vitaminB3: "0.053mg",
    vitaminB5: "0.0mg",
    vitaminB6: "0.024mg",
    vitaminB9: "0.00057mg",
    vitaminB12: "0.0mg",
    vitaminC: "0.9mg",
    vitaminD: "0.0mg",
    vitaminE: "0.05mg",
    vitaminK: "0.0041mg",
    betaine: "0.0mg",
    choline: "1.6mg",
    calcium: "2.83mg",
    copper: "0.036mg",
    fluoride: "0.0mg",
    iron: "0.10mg",
    magnesium: "1.98mg",
    manganese: "0.0mg",
    phosphorus: "5.67mg",
    potassium: "54.15mg",
    selenium: "0.0mg",
    sodium: "0.57mg",
    zinc: "0.02mg",
    protein: "0.20g"
  },
  Grapefruit: {
    calories: 12,
    totalCarbohydrate: "3.02g",
    sugar: "1.95g",
    totalFat: "0.05g",
    vitaminA: "0.01644mg",
    vitaminB1: "0.012mg",
    vitaminB2: "0.009mg",
    vitaminB3: "0.058mg",
    vitaminB5: "0.0mg",
    vitaminB6: "0.015mg",
    vitaminB9: "0.00369mg",
    vitaminB12: "0.0mg",
    vitaminC: "8.8mg",
    vitaminD: "0.0mg",
    vitaminE: "0.04mg",
    vitaminK: "0.0mg",
    betaine: "0.0mg",
    choline: "2.2mg",
    calcium: "6.24mg",
    copper: "0.009mg",
    fluoride: "0.0mg",
    iron: "0.02mg",
    magnesium: "2.55mg",
    manganese: "0.0mg",
    phosphorus: "5.10mg",
    potassium: "38.27mg",
    selenium: "0.0mg",
    sodium: "0.0mg",
    zinc: "0.02mg",
    protein: "0.22g"
  },
  "Honeydew Melon": {
    calories: 10,
    totalCarbohydrate: "2.58g",
    sugar: "2.30g",
    totalFat: "0.04g",
    vitaminA: "0.00085mg",
    vitaminB1: "0.011mg",
    vitaminB2: "0.003mg",
    vitaminB3: "0.119mg",
    vitaminB5: "0.0mg",
    vitaminB6: "0.025mg",
    vitaminB9: "0.00539mg",
    vitaminB12: "0.0mg",
    vitaminC: "5.1mg",
    vitaminD: "0.0mg",
    vitaminE: "0.01mg",
    vitaminK: "0.0008mg",
    betaine: "0.0mg",
    choline: "2.2mg",
    calcium: "1.70mg",
    copper: "0.007mg",
    fluoride: "0.0mg",
    iron: "0.05mg",
    magnesium: "2.83mg",
    manganese: "0.0mg",
    phosphorus: "3.12mg",
    potassium: "64.64mg",
    selenium: "0.0002mg",
    sodium: "5.10mg",
    zinc: "0.03mg",
    protein: "0.15g"
  },
  Kale: {
    calories: 9.9,
    totalCarbohydrate: "1.25g",
    sugar: "0.28g",
    totalFat: "0.42g",
    vitaminA: "0.06832mg",
    vitaminB1: "0.032mg",
    vitaminB2: "0.098mg",
    vitaminB3: "0.335mg",
    vitaminB5: "0.105mg",
    vitaminB6: "0.042mg",
    vitaminB9: "0.01758mg",
    vitaminB12: "0.0mg",
    vitaminC: "26.5mg",
    vitaminD: "0.0mg",
    vitaminE: "0.19mg",
    vitaminK: "0.1104mg",
    betaine: "0.1mg",
    choline: "0.1mg",
    calcium: "72.01mg",
    copper: "0.015mg",
    fluoride: "0.0mg",
    iron: "0.45mg",
    magnesium: "9.36mg",
    manganese: "0.261mg",
    phosphorus: "15.59mg",
    potassium: "98.66mg",
    selenium: "0.0003mg",
    sodium: "15.03mg",
    zinc: "0.11mg",
    protein: "0.83g",
  },
  Kiwi: {
    calories: 16,
    totalCarbohydrate: "3.97g",
    sugar: "2.55g",
    totalFat: "0.12g",
    vitaminA: "0.00113mg",
    vitaminB1: "0.008mg",
    vitaminB2: "0.007mg",
    vitaminB3: "0.105mg",
    vitaminB5: "0.0mg",
    vitaminB6: "0.017mg",
    vitaminB9: "0.00737mg",
    vitaminB12: "0.0mg",
    vitaminC: "21.2mg",
    vitaminD: "0.0mg",
    vitaminE: "0.37mg",
    vitaminK: "0.0114mg",
    betaine: "0.0mg",
    choline: "2.2mg",
    calcium: "9.92mg",
    copper: "0.038mg",
    fluoride: "0.0mg",
    iron: "0.07mg",
    magnesium: "4.54mg",
    manganese: "0.0mg",
    phosphorus: "9.64mg",
    potassium: "56.13mg",
    selenium: "0.0001mg",
    sodium: "1.42mg",
    zinc: "0.04mg",
    protein: "0.30g"
  },
  Lemons: {
    calories: 8.2,
    totalCarbohydrate: "2.64g",
    sugar: "0.71g",
    totalFat: "0.09g",
    vitaminA: "0.00028mg",
    vitaminB1: "0.011mg",
    vitaminB2: "0.006mg",
    vitaminB3: "0.028mg",
    vitaminB5: "0.0mg",
    vitaminB6: "0.023mg",
    vitaminB9: "0.00312mg",
    vitaminB12: "0.0mg",
    vitaminC: "15..0mg",
    vitaminD: "0.0mg",
    vitaminE: "0.04mg",
    vitaminK: "0.0mg",
    betaine: "0.0mg",
    choline: "1.4mg",
    calcium: "7.37mg",
    copper: "0.010mg",
    fluoride: "0.0mg",
    iron: "0.17mg",
    magnesium: "2.27mg",
    manganese: "0.0mg",
    phosphorus: "4.54mg",
    potassium: "39.12mg",
    selenium: "0.0001mg",
    sodium: "0.57mg",
    zinc: "0.02mg",
    protein: "0.31g",
  },
  Lime: {
    calories: 8.5,
    totalCarbohydrate: "2.99g",
    sugar: "0.48g",
    totalFat: "0.06g",
    vitaminA: "0.00057mg",
    vitaminB1: "0.009mg",
    vitaminB2: "0.006mg",
    vitaminB3: "0.057mg",
    vitaminB5: "0.0mg",
    vitaminB6: "0.012mg",
    vitaminB9: "0.00227mg",
    vitaminB12: "0.0mg",
    vitaminC: "8.2mg",
    vitaminD: "0.0mg",
    vitaminE: "0.06mg",
    vitaminK: "0.0002mg",
    betaine: "0.0mg",
    choline: "1.4mg",
    calcium: "9.36mg",
    copper: "0.018mg",
    fluoride: "0mg",
    iron: "0.17mg",
    magnesium: "1.7mg",
    manganese: "0mg",
    phosphorus: "5.1mg",
    potassium: "28.92mg",
    selenium: "0.00011mg",
    sodium: "0.57mg",
    zinc: "0.03mg",
    protein: "0.2g"
  },
  Mango: {
    calories: 17,
    totalCarbohydrate: "4.3g",
    sugar: "3.9g",
    totalFat: "0.1g",
    vitaminA: "0.01531mg",
    vitaminB1: "0.008mg",
    vitaminB2: "0.011mg",
    vitaminB3: "0.190mg",
    vitaminB5: "0.056mg",
    vitaminB6: "0.034mg",
    vitaminB9: "0.01219mg",
    vitaminB12: "0mg",
    vitaminC: "10.3mg",
    vitaminD: "0mg",
    vitaminE: "0.26mg",
    vitaminK: "0.0012mg",
    betaine: "0mg",
    choline: "2.2mg",
    calcium: "3.12mg",
    copper: "0.03mg",
    fluoride: "0mg",
    iron: "0.05mg",
    magnesium: "2.83mg",
    manganese: "0.018mg",
    phosphorus: "3.97mg",
    potassium: "47.63mg",
    selenium: "0.00017mg",
    sodium: "028mg",
    zinc: "0.03mg",
    protein: "0.23g"
  },
  Oranges: {
    calories: 13,
    totalCarbohydrate: "3.3g",
    sugar: "2.7g",
    totalFat: "0g",
    vitaminA: "0.00312mg",
    vitaminB1: "0.025mg",
    vitaminB2: "0.011mg",
    vitaminB3: "0.08mg",
    vitaminB5: "0mg",
    vitaminB6: "0.017mg",
    vitaminB9: "0.0085mg",
    vitaminB12: "0mg",
    vitaminC: "15.1mg",
    vitaminD: "0mg",
    vitaminE: "0.05mg",
    vitaminK: "0mg",
    betaine: "0mg",
    choline: "2.4mg",
    calcium: "11.34mg",
    copper: "0.01mg",
    fluoride: "0mg",
    iron: "0.03mg",
    magnesium: "2.83mg",
    manganese: "0mg",
    phosphorus: "3.97mg",
    potassium: "51.31mg",
    selenium: "0.00014mg",
    sodium: "0mg",
    zinc: "0.02mg",
    protein: "0.27g"
  },
  Pineapple: {
    calories: 14,
    totalCarbohydrate: "3.7g",
    sugar: "2.8g",
    totalFat: "0g",
    vitaminA: "0.00085mg",
    vitaminB1: "0.022mg",
    vitaminB2: "0.009mg",
    vitaminB3: "0.142mg",
    vitaminB5: "0mg",
    vitaminB6: "0.032mg",
    vitaminB9: "0.0051mg",
    vitaminB12: "0mg",
    vitaminC: "13.6mg",
    vitaminD: "0mg",
    vitaminE: "0.01mg",
    vitaminK: "0.0002mg",
    betaine: "0mg",
    choline: "1.6mg",
    calcium: "3.69mg",
    copper: "0.03mg",
    fluoride: "0mg",
    iron: "0.08mg",
    magnesium: "3.40mg",
    manganese: "0mg",
    phosphorus: "2.27mg",
    potassium: "30.9mg",
    selenium: "0.00003mg",
    sodium: "0.28mg",
    zinc: "0.03mg",
    protein: "0.15g"
  },
  Peaches: {
    calories: 12,
    totalCarbohydrate: "2.9g",
    sugar: "2.4g",
    totalFat: "0.1g",
    vitaminA: "0.0068mg",
    vitaminB1: "0.007mg",
    vitaminB2: "0.009mg",
    vitaminB3: "0.228mg",
    vitaminB5: "0mg",
    vitaminB6: "0.007mg",
    vitaminB9: "0.0017mg",
    vitaminB12: "0mg",
    vitaminC: "1.2mg",
    vitaminD: "0mg",
    vitaminE: "0.21mg",
    vitaminK: "0.0009mg",
    betaine: "0mg",
    choline: "1.7mg",
    calcium: "1.13mg",
    copper: "0.02mg",
    fluoride: "0mg",
    iron: "0.1mg",
    magnesium: "2.27mg",
    manganese: "0mg",
    phosphorus: "6.24mg",
    potassium: "34.59mg",
    selenium: "0.0006mg",
    sodium: "3.69mg",
    zinc: "0.07mg",
    protein: "0.26g"
  },
  Pears: {
    calories: 16,
    totalCarbohydrate: "4.3g",
    sugar: "2.8g",
    totalFat: "0g",
    vitaminA: "0.0028mg",
    vitaminB1: "0.003mg",
    vitaminB2: "0.007mg",
    vitaminB3: "0.046mg",
    vitaminB5: "0mg",
    vitaminB6: "0.008mg",
    vitaminB9: "0.00198mg",
    vitaminB12: "0mg",
    vitaminC: "1.2mg",
    vitaminD: "0mg",
    vitaminE: "0.03mg",
    vitaminK: "0.0012mg",
    betaine: "0mg",
    choline: "1.4mg",
    calcium: "2.55mg",
    copper: "0.02mg",
    fluoride: "0mg",
    iron: "0.05mg",
    magnesium: "1.98mg",
    manganese: "0mg",
    phosphorus: "3.4mg",
    potassium: "32.89mg",
    selenium: "0.00003mg",
    sodium: "0.28mg",
    zinc: "0.03mg",
    protein: "0.1g"
  },
  Strawberries: {
    calories: 9.1,
    totalCarbohydrate: "2.2g",
    sugar: "1.4g",
    totalFat: "0.1g",
    vitaminA: "0.00028mg",
    vitaminB1: "0.007mg",
    vitaminB2: "0.006mg",
    vitaminB3: "0.109mg",
    vitaminB5: "0.035mg",
    vitaminB6: "0.013mg",
    vitaminB9: "0.0068mg",
    vitaminB12: "0mg",
    vitaminC: "16.7mg",
    vitaminD: "0mg",
    vitaminE: "0.08mg",
    vitaminK: "0.0006mg",
    betaine: "0.1mg",
    choline: "1.6mg",
    calcium: "4.54mg",
    copper: "0.01mg",
    fluoride: "0.0012mg",
    iron: "0.12mg",
    magnesium: "3.69mg",
    manganese: "0.109mg",
    phosphorus: "6.80mg",
    potassium: "43.37mg",
    selenium: "0.00011mg",
    sodium: "0.28mg",
    zinc: "0.04mg",
    protein: "0.19g"
  },
  Watermelon: {
    calories: 8.5,
    totalCarbohydrate: "2.1g",
    sugar: "1.8g",
    totalFat: "0g",
    vitaminA: "0.00794mg",
    vitaminB1: "0.009mg",
    vitaminB2: "0.006mg",
    vitaminB3: "0.050mg",
    vitaminB5: "0.063mg",
    vitaminB6: "0.013mg",
    vitaminB9: "0.00085mg",
    vitaminB12: "0mg",
    vitaminC: "2.3mg",
    vitaminD: "0mg",
    vitaminE: "0.01mg",
    vitaminK: "0mg",
    betaine: "0.1mg",
    choline: "1.2mg",
    calcium: "1.98mg",
    copper: "0.01mg",
    fluoride: "0.0004mg",
    iron: "0.07mg",
    magnesium: "2.83mg",
    manganese: "0.011mg",
    phosphorus: "3.12mg",
    potassium: "31.75mg",
    selenium: "0.00011mg",
    sodium: "0.28mg",
    zinc: "0.03mg",
    protein: "0.17g"
  },
};

export const list = {

  "Red Delicious Apple": {
    img: redDeliciousApple,
    calories: 18,
    totalCarbohydrate: "4.2g",
    sugar: "2.97g",
    totalFat: "0.1g",
    protein: "0.05g",
    facts: [
    "Apples contain quercetin, which may have \
    anti-inflammatory, antiviral, anticancer, and antidepressant \
    effects, according to animal studies.",
    "Apples contains catechin, an antioxidant \
    hathat has been shown to improve brain \
    and muscle function in animal studies.",
    "Apples contain bioactive compounds \
    that may help promote healthful gut bacteria, which may help \
    optimize the health of people with obesity.", 
 ],
    
    color: "#ac7648",//"#af7605"
    costPerOunce: 0.27,
  },
  "Granny Smith Apple": {
    img: grannySmithApple,
    calories: 16,
    totalCarbohydrate: "3.9g",
    sugar: "2.9g",
    totalFat: "0g",
    protein: "0.08g",
    facts: ["Contains chlorogenic acid which has been found to \
    lower blood sugar and cause weight loss in some studies.",
  "Many test-tube and animal studies suggest that apple phytonutrients \
  can protect against cancers of the lungs and colon."],
    taste: "sour",
    color: "#e0e7a1",//"#ebb107"
    costPerOunce: 0.31,
  },
  Beets: {
    img: beets,
    calories: 12,
    totalCarbohydrate: "2.71g",
    sugar: "1.92g",
    totalFat: "0.05g",
    protein: "0.46g",
    facts: [
      "Some studies have found that beetroot juice \
    supplementation can improve the amount of oxygen that \
    muscles absorb during exercise.",
      "They’re low in calories yet high in valuable vitamins and \
    minerals. In fact, they contain a bit of almost all of the \
    vitamins and minerals your body need.",
      "A 2019 review of studies\
     found that certain compounds in beets can disrupt the cancerous \
     mutations of cells. Such compounds include betalains, which are pigments \
     that give beets their red and yellow color. Betalains\
     possess a number of anti-inflammatory properties.",
      "High in copper, an important mineral required for energy production and \
     the synthesis of certain neurotransmitters.",
    ],
    
    color: "#360302",//"#cc253d",
    costPerOunce: 0.35,
    taste: "earthy"
  },
  Cantaloupe: {
    img: cantaloupe,
    calories: 9.6,
    totalCarbohydrate: "2.31g",
    sugar: "2.23g",
    totalFat: "0.05g",
    protein: "0.24g",
    facts: [
      "Great source of vitamin A and C, and vitamin B9.",
      "Cantaloupes are filled with electrolytes.",
      "Compounds called phytonutrients in cantaloupes give\
   it anti-inflammatory properties.",
    ],
    
    color: "#d3673d",//"#f88c18",
    costPerOunce: 0.29,
  },
  Carrot: {
    img: carrots,
    calories: 12,
    totalCarbohydrate: "2.72g",
    sugar: "1.34g",
    totalFat: "0.07g",
    protein: "0.26g",
    facts: [
      "Carrots contain vitamin A, and a vitamin A deficiency may\
     result in xerophthalmia, a progressive eye disease. \
      According to the Office of Dietary Supplements, a lack \
      of vitamin A is one of the main preventable causes of blindness in children.",
      "Carrots offer many plant compounds, including carotenoids. These are substances with powerful antioxidant activity that have been\
     linked to improved immune function and reduced risk of many illnesses, \
     including heart disease, various degenerative ailments, and certain types of cancer.",
      "In one study, researchers looked at the effect of carrot juice extracts on leukemia cells.\
     The carrot juice extracts caused the leukemia cells to self-destruct and stopped their cell cycle.",
      "Researchers reported that higher levels of carotenoids in the blood were associated with a lower risk of breast cancer returning.",
    ],
    
    color: "#ae4800",//"#f3881d",
    costPerOunce: 0.28,
  },
  Celery: {
    img: celery,
    calories: 4,
    totalCarbohydrate: "0.84g",
    sugar: "0.38g",
    totalFat: "0.05g",
    protein: "0.20g",
    facts: [
      "A wonderful source of phytonutrients, which have been \
    shown to reduce instances of inflammation in the digestive tract,\
     cells, blood vessels, and organs.",
      "Celery is rich in vitamins and minerals.",
      "Celery is rich in a phytochemical known as phthalides. This\
     compound is thought to relax artery wall tissues to promote \
     healthy blood flow.",
    ],
    
    color: "#7e8b41",//"#7bb604",
    costPerOunce: 0.26,
  },
  Cucumber: {
    img: cucumber,
    calories: 4.3,
    totalCarbohydrate: "1.03g",
    sugar: "0.47g",
    totalFat: "0.03g",
    protein: "0.18g",
    facts: [
      "Cucumbers are low in calories, high in water and \
    contain important electrolytes. They can help \
    prevent dehydration in hot weather or after a workout.",
      "Studies have suggested that the lignans in \
  cucumber and other foods may help lower the risk of cardiovascular \
  disease and several types of cancer.",
      "High in Vitamin K. May help with blood clotting, and it support bone health.",
    ],
    
    color: "#737e1e",//"#b1c91e",
    costPerOunce: 0.25,
  },
  Ginger: {
    img: ginger,
    calories: 23,
    totalCarbohydrate: "5.04g",
    sugar: "0.48g",
    totalFat: "0.21g",
    protein: "0.52g",
    facts: [
      "Ginger is high in gingerol, a substance\
     with powerful anti-inflammatory and antioxidant properties.",
      "Good for digestion. Some research indicates that enzymes \
    in ginger can help the body break up and expel this gas, \
    providing relief from any discomfort.",
      "Ginger appears to be highly effective against nausea. May be \
  the most effective when it comes to pregnancy-related nausea,\
   such as morning sickness.",
      "May relieve pain.",
    ],
    taste: "extremely spicy",
    color: "#dec152",//"#d3ba76",
    costPerOunce: 0.60,
  },
  "Green Grapes": {
    img: greenGrapes,
    calories: 20,
    totalCarbohydrate: "5.13g",
    sugar: "4.39g",
    totalFat: "0.05g",
    protein: "0.20g",
    facts: [
      "Grapes contain compounds that may improve memory, \
    attention, and mood, as well as protect against Alzheimer’s disease.",
      "Compounds in grapes with antimicrobial activity include \
  anthocyanins, which may destroy bacterial cell walls.",
      "Antioxidants in grapes may combat obesity by inhibiting appetite and \
preventing weight gain. However, research in humans is lacking.",
      "Grapes are a natural source of melatonin, a hormone that may improve your sleep quality.",
    ],
    
    color: "#9ab56b",//"#c8cf3e",
    costPerOunce: 0.40,
  },
  "Red Grapes": {
    img: redGrapes,
    calories: 20,
    totalCarbohydrate: "5.13g",
    sugar: "4.39g",
    totalFat: "0.05g",
    protein: "0.20g",
    facts: [
      "The skins of red grapes contain \
    the phytochemical resveratrol, which appears \
    to protect against several chronic diseases and conditions.",
      "The skins of red grapes contain the phytochemical resveratrol,\
   which appears to protect against several chronic diseases and conditions.",
      "Compounds found in grapes may help protect against high cholesterol \
  levels by decreasing cholesterol absorption.",
    ],
    
    color: "#c9775a",//"#b33133",
    costPerOunce: 0.35,
  },
  Grapefruit: {
    img: grapefruit,
    calories: 12,
    totalCarbohydrate: "3.02g",
    sugar: "1.95g",
    totalFat: "0.05g",
    protein: "0.22g",
    facts: [
      "Eating grapefruit regularly may \
    have the potential to prevent insulin resistance,\
     which can lead to diabetes.",
      "Grapefruit contains several types of antioxidants \
    that may help prevent the development of some chronic \
    conditions, including heart disease and cancer.",
      "The citric acid in grapefruit may help reduce the \
  formation of calcium oxalate kidney stones.",
    ],
    
    color: "#f27861",//"#f07f52",
    costPerOunce: 0.34,
  },
  "Honeydew Melon": {
    img: honeydew,
    calories: 10,
    totalCarbohydrate: "2.58g",
    sugar: "2.30g",
    totalFat: "0.04g",
    protein: "0.15g",
    facts: [
      "Honeydew melon is a low-sodium and potassium-rich fruit,\
     it may help you maintain healthy blood pressure levels.",
      "Honeydew contains multiple nutrients that are vital for\
     bone health, including vitamin B9, vitamin K and magnesium.",
      "Honeydew melon is about 90% water and contains electrolytes,\
      such as potassium, magnesium, sodium and calcium.",
    ],
    
    color: "#676f1a",
    costPerOunce: 0.30,
  },
  Kale: {
    img: kale,
    calories: 9.9,
    totalCarbohydrate: "1.25g",
    sugar: "0.28g",
    totalFat: "0.42g",
    protein: "0.83g",
    facts: [
      "Kale is very high in nutrients and very low in calories, \
    making it one of the most nutrient-dense foods on the planet. Many\
     powerful antioxidants are found in kale, including quercetin and\
      kaempferol, which have numerous beneficial effects on health.",
      "Kale is extremely high in vitamin C, an antioxidant that has\
     many important roles in the body.",
      "Kale contains substances that bind bile acids and lower \
    cholesterol levels in the body.",
      "Kale contains sulforaphane, a substance that has been shown \
  to help fight the formation of cancer at the molecular level.",
      "Kale is high in minerals, some of which many people are deficient in.\
Calcium, potassium and magnesium.",
      "Kale is high in lutein and zeaxanthin, nutrients that have been linked \
to a drastically reduced risk of macular degeneration and cataracts.",
    ],
    
    color: "#181e00",
    costPerOunce: 0.75,
  },
  Kiwi: {
    img: kiwi,
    calories: 16,
    totalCarbohydrate: "3.97g",
    sugar: "2.55g",
    totalFat: "0.12g",
    protein: "0.30g",
    facts: [
      "Kiwi are exceptionally high in vitamin C.",
      "Kiwi contain potassium, copper, vitamin K, vitamin B9, \
  and vitamin E, a fat-soluble nutrient that has antioxidant\
   effects and plays an important role in immune health.",
      "Kiwi contain carotenoids. Studies show that diets high in carotenoids \
  may help protect against certain health conditions, including heart disease.",
      "Kiwellin and kissper are proteins in kiwi that may have anti-inflammatory properties.",
      "Kiwi contains vitamin K and traces of calcium and phosphorus, all of which contribute to bone health.",
    ],
    
    color: "#8d9735",
    costPerOunce: 0.60,
  },
  Lemons: {
    img: lemons,
    calories: 8.2,
    totalCarbohydrate: "2.64g",
    sugar: "0.71g",
    totalFat: "0.09g",
    protein: "0.31g",
    facts: [
      "Lemons are high in heart-healthy vitamin C\
    and several beneficial plant compounds may lower cholesterol and \
    boost immune system.",
      "Some studies have found that lemonade effectively prevented kidney \
  stones, but the results have been mixed.",
    ],
    
    color: "#c0c5b6",
    costPerOunce: 0.76,
  },
  Lime: {
    img: lime,
    calories: 8.5,
    totalCarbohydrate: "2.99g",
    sugar: "0.48g",
    totalFat: "0.06g",
    protein: "g",
    facts: [
      "One lime can provide 32 percent of the vitamin C needed in a day.",
      "The nutrients in limes can support heart, reduce the risk of asthma,\
   and promote healthy skin.",
      "Many studies have suggested that increasing consumption \
   of plant foods like limes decreases the risk of obesity, diabetes, heart disease, and\
    overall mortality while promoting a healthy complexion and hair, increased energy, \
    and lower overall weight.",
    ],
    
    color: "#afab82",
    costPerOunce: 0.46,
  },
  Mango: {
    img: mango,
    calories: 14,
    totalCarbohydrate: "3.7g",
    sugar: "2.8g",
    totalFat: "g",
    protein: "g",
    facts: ["High in vitamin C, \
     which aids immunity, iron absorption, and cell growth and repair.",
     "Mangoes are packed with polyphenols, which are plant compounds that \
     act as antioxidants to protect your body.",
     "Among the polyphenols, mangiferin has gained the most \
     interest and is sometimes called a “super antioxidant” since it’s especially powerful.",
     "Contains magnesium and potassium, which help maintain a healthy blood flow."
    ],
    
    color: "#e5aa28",
    costPerOunce: 0.60,
  },
  Oranges: {
    img: oranges,
    calories: 12,
    totalCarbohydrate: "g",
    sugar: "g",
    totalFat: "g",
    protein: "g",
    facts: [
      "Excellent source of vitamin C. \
    Higher dietary intake and blood concentrations \
    of vitamin C have been linked to a lower risk of heart\
     disease, cancer, and death from all causes.",
      "Although oranges\
     are not a good source of iron, the vitamin C within oranges, \
      enhances your body’s ability to absorb iron.",
    ],
    
    color: "#dba81f",
    costPerOunce: 0.58,
  },
  Pineapple: {
    img: pineapple,
    calories: 14,
    totalCarbohydrate: "3.7g",
    sugar: "2.8g",
    totalFat: "g",
    protein: "g",
    facts: [
      "Many studies have suggested that increasing \
    consumption of plant foods like pineapples decreases \
    the risk of obesity, overall mortality, diabetes, and heart disease.",
      "May promote a healthy complexion and hair, increased energy, and \
  an overall lower weight.",
      "Pineapples contain bromelain, a group of digestive enzymes that may \
 help break down protein and aid digestion. Bromelain’s anti-inflammatory\
  properties may provide pain \
relief for those with inflammatory arthritis.",
    ],
    
    color: "#aca266",
    costPerOunce: 0.41,
  },
  Peaches: {
    img: peaches,
    calories: 12,
    totalCarbohydrate: "g",
    sugar: "g",
    totalFat: "g",
    protein: "g",
    facts: [
      "Contain beneficial plant compounds like antioxidants,\
     which can help protect your body from aging and disease.",
      "Studies indicate that compounds found in peaches may improve\
     your skin’s ability to retain moisture — thus improving skin texture.",
      "Research shows that peaches may help reduce allergy symptoms by\
     preventing the release of histamines in the blood.\
     Histamines are part of your body’s defense system and trigger \
     allergy symptoms like sneezing, itching, or coughing.",
      "Peaches may boost immunuity, protect against against certain toxins,\
    and reduce blood sugar levels.",
    ],
    
    color: "#ee6a07",
    costPerOunce: 0.54,
  },
  Pears: {
    img: pears,
    taste: "Best tasting",
    calories: 12,
    totalCarbohydrate: "g",
    sugar: "g",
    totalFat: "g",
    protein: "g",
    facts: [
      "Green pears may promote eye health.",
      "Pears contain high levels of antioxidants, \
    including vitamin C, vitamin K, and copper.\
    These chemicals counter the effects of free radicals,\
    protecting cells from the damage they can cause. Free radicals \
    develop when the body converts food to energy, and they can \
    contribute to cancer growth.",
      "Pears are a rich source of flavonoid antioxidants, which \
  help fight inflammation and may decrease your risk of disease.",
    ],
    
    color: "#dcb049",
    costPerOunce: 0.40,
  },
  Strawberries: {
    img: strawberries,
    calories: 12,
    totalCarbohydrate: "g",
    sugar: "g",
    totalFat: "g",
    protein: "g",
    facts: [
      "Ingredients within strawberries may also \
    help protect against heart disease, stroke, cancer, \
    high blood pressure, and constipation.",
      "Evidence suggests strawberries \
  lowers the post-meal increase in blood sugar\
   in some people with obesity or excess weight.",
      "Excellent source of vitamin C, potassium, and antioxidants.",
    ],
    
    color: "#f17263",
    costPerOunce: 0.49,
  },
  Watermelon: {
    img: watermelon,
    calories: 8.5,
    totalCarbohydrate: "2.1g",
    sugar: "1.8g",
    totalFat: "0g",
    protein: "g",
    facts: [
      "Good source of Vitamin A and C.",
      "A rich source of citrulline, an amino acid that\
     may improve exercise performance.",
      "The combination of antioxidants, lycopene,\
      and vitamin C in watermelon may help lower \
      inflammation and oxidative damage."
    ],
    
    color: "#c92a28",
    costPerOunce: 0.35,
  },
};
